/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.jimaginary.machine.graph.params;

import com.jimaginary.machine.graph.viewer.ParameterPropertyEditor;
import com.jimaginary.machine.math.MathFunction;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author simonkenny
 */
public class ProbTableParamPropertyPanel extends javax.swing.JPanel {

    private final MathFunction mathFunc;
    private final ParameterPropertyEditor editor;
    
    /**
     * Creates new form ProbTableParamPropertyPanel
     */
    public ProbTableParamPropertyPanel(String []idxNames, MathFunction mathFunc, ParameterPropertyEditor editor) {
        initComponents();
        this.editor = editor;
        this.mathFunc = mathFunc;
        jTableData.setShowGrid(true);
        DefaultTableModel dtm = (DefaultTableModel)jTableData.getModel();
        for( int i = 0 ; i < mathFunc.getNumParameters() ; i++ ) {
            dtm.addRow(new Object[]{
                idxNames != null ? idxNames[i] : mathFunc.getParamName(i),
                mathFunc.getParameter(i)
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableData = new javax.swing.JTable();
        jButtonValidate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ProbTableParamPropertyPanel.class, "ProbTableParamPropertyPanel.jLabel1.text")); // NOI18N

        jTableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Probability"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableData.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jTableData);
        if (jTableData.getColumnModel().getColumnCount() > 0) {
            jTableData.getColumnModel().getColumn(0).setResizable(false);
            jTableData.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(ProbTableParamPropertyPanel.class, "ProbTableParamPropertyPanel.jTableData.columnModel.title0")); // NOI18N
            jTableData.getColumnModel().getColumn(1).setResizable(false);
            jTableData.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(ProbTableParamPropertyPanel.class, "ProbTableParamPropertyPanel.jTableData.columnModel.title1")); // NOI18N
        }

        org.openide.awt.Mnemonics.setLocalizedText(jButtonValidate, org.openide.util.NbBundle.getMessage(ProbTableParamPropertyPanel.class, "ProbTableParamPropertyPanel.jButtonValidate.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jButtonValidate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonValidate))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonValidate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableData;
    // End of variables declaration//GEN-END:variables
}
